### ISSUE TITLE
new new split horizon

### ISSUE THREAD

**Issue by rjbs** [rjbs/DNS-Oterica#1]
``` yaml
    ---
    domain: fx.com
    hostname: dstore0
    ip:
      FALLBACK: 208.72.237.95
        #95...208.in-addr --> dstore0.fx.com
      europe:
        ip: 123.123.123.2
        #2.321.321.321.in-addr --> dstore0.fx.com
      quonix:
        private-ptr: true
        ip: 10.80.80.14
        domain: int.fx.com
        #14.80.80.10.in-addr --> dstore0.int.fx.com
    aliases:
      - a-dstore-quonix.fx.com
    location: quonix
    families:
      - com.fx.dstore
      - com.fx.outbound
```
# TODO:
- add hostname/domain to each location on a host, which become A records _only_
  at that location
- add aliases to each location, similarly?
- PTR records are **not** limited by the ip location, they are served to
  everyone (10.x/8 are limited by virtue of delegation from the root!)
- can we set default domain and ptr on an ip based on its network?
  (e.g., quonix are always private-ptr and domain = int.icgroup.com)
- we don't want people directly asking our tinydns servers about ptrs for our
  internal names
